import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="w-full flex items-center justify-between px-6 py-4 bg-gradient-to-r from-violet-600 to-purple-700 text-white shadow-md sticky top-0 z-50">
          <a href="/" className="flex items-center gap-2">
            <Image
              src="/favicon-jul18-litends-edition1.svg"
              alt="Litends Logo"
              width={40}
              height={40}
              className="rounded-xl drop-shadow"
              priority
            />
            <span className="text-xl font-bold tracking-wide hidden sm:inline">Litends</span>
          </a>
          <ul className="flex gap-8 text-lg font-semibold">
            <li><a href="/" className="hover:text-purple-200 transition">Home</a></li>
            <li><a href="/services" className="hover:text-purple-200 transition">Services</a></li>
            <li><a href="/about" className="hover:text-purple-200 transition">About</a></li>
            <li><a href="/contact" className="hover:text-purple-200 transition">Contact</a></li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
